openapi: 3.0.0
info:
  title: SimpleAiTranslate Internal API
  description: Internal API contracts for SimpleAiTranslate Chrome extension components
  version: 1.0.0

paths:
  # AI Provider Management
  /api/providers:
    get:
      summary: Get all AI providers
      description: Retrieve list of configured AI providers
      responses:
        '200':
          description: List of AI providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AIProvider'
    
    post:
      summary: Add new AI provider
      description: Configure a new AI provider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AIProviderInput'
      responses:
        '201':
          description: Provider created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AIProvider'
        '400':
          description: Invalid provider configuration

  /api/providers/{providerId}:
    put:
      summary: Update AI provider
      description: Update existing AI provider configuration
      parameters:
        - name: providerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AIProviderInput'
      responses:
        '200':
          description: Provider updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AIProvider'
        '404':
          description: Provider not found
    
    delete:
      summary: Delete AI provider
      description: Remove AI provider configuration
      parameters:
        - name: providerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Provider deleted successfully
        '404':
          description: Provider not found

  # Translation Operations
  /api/translate:
    post:
      summary: Translate text
      description: Send translation request to AI provider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslationRequest'
      responses:
        '200':
          description: Translation completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranslationResult'
        '400':
          description: Invalid translation request
        '500':
          description: Translation service error

  # User Settings
  /api/settings:
    get:
      summary: Get user settings
      description: Retrieve current user preferences
      responses:
        '200':
          description: User settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettings'
    
    put:
      summary: Update user settings
      description: Modify user preferences
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSettingsInput'
      responses:
        '200':
          description: Settings updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettings'

  # Translation History
  /api/history:
    get:
      summary: Get translation history
      description: Retrieve user's translation history
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Translation history
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TranslationHistory'

  /api/history/{historyId}:
    delete:
      summary: Delete history entry
      description: Remove specific translation history entry
      parameters:
        - name: historyId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: History entry deleted successfully
        '404':
          description: History entry not found

components:
  schemas:
    AIProvider:
      type: object
      required:
        - id
        - name
        - baseUrl
        - model
        - isActive
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
        baseUrl:
          type: string
          format: uri
        apiKey:
          type: string
          description: Encrypted API key
        model:
          type: string
          minLength: 1
        isActive:
          type: boolean
          default: true
        customPrompt:
          type: string
        settings:
          type: object
          additionalProperties: true

    AIProviderInput:
      type: object
      required:
        - name
        - baseUrl
        - model
      properties:
        name:
          type: string
          minLength: 1
        baseUrl:
          type: string
          format: uri
        apiKey:
          type: string
        model:
          type: string
          minLength: 1
        customPrompt:
          type: string
        settings:
          type: object
          additionalProperties: true

    TranslationRequest:
      type: object
      required:
        - selectedText
        - contextText
        - requestType
        - providerId
      properties:
        id:
          type: string
          format: uuid
        selectedText:
          type: string
          minLength: 1
        contextText:
          type: string
          minLength: 1
        wordPosition:
          type: integer
          minimum: 0
        requestType:
          type: string
          enum: [word, sentence, paragraph]
        timestamp:
          type: string
          format: date-time
        providerId:
          type: string
          format: uuid
        status:
          type: string
          enum: [pending, processing, completed, failed]
          default: pending

    TranslationResult:
      type: object
      required:
        - requestId
        - translatedText
        - confidence
      properties:
        id:
          type: string
          format: uuid
        requestId:
          type: string
          format: uuid
        translatedText:
          type: string
          minLength: 1
        ipaPronunciation:
          type: string
        confidence:
          type: number
          minimum: 0
          maximum: 1
        providerResponse:
          type: object
        timestamp:
          type: string
          format: date-time

    UserSettings:
      type: object
      required:
        - id
        - defaultProviderId
        - autoSync
      properties:
        id:
          type: string
          format: uuid
        defaultProviderId:
          type: string
          format: uuid
        autoSync:
          type: boolean
        syncInterval:
          type: integer
          minimum: 1
          maximum: 1440
          default: 60
        theme:
          type: string
          enum: [light, dark, system]
          default: system
        language:
          type: string
          default: en
        privacySettings:
          type: object
          properties:
            shareAnalytics:
              type: boolean
              default: false
            shareUsageData:
              type: boolean
              default: false
        performanceSettings:
          type: object
          properties:
            enableCache:
              type: boolean
              default: true
            cacheSize:
              type: integer
              minimum: 10
              maximum: 1000
              default: 100

    UserSettingsInput:
      type: object
      properties:
        defaultProviderId:
          type: string
          format: uuid
        autoSync:
          type: boolean
        syncInterval:
          type: integer
          minimum: 1
          maximum: 1440
        theme:
          type: string
          enum: [light, dark, system]
        language:
          type: string
        privacySettings:
          type: object
        performanceSettings:
          type: object

    TranslationHistory:
      type: object
      required:
        - id
        - originalText
        - translatedText
        - providerId
      properties:
        id:
          type: string
          format: uuid
        originalText:
          type: string
          minLength: 1
        translatedText:
          type: string
          minLength: 1
        contextText:
          type: string
        timestamp:
          type: string
          format: date-time
        providerId:
          type: string
          format: uuid
        isBookmarked:
          type: boolean
          default: false
        isSynced:
          type: boolean
          default: false